apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: pet-onboarding-config
spec:
  healthCheck:
    checkIntervalSec: 60
    type: HTTP
    requestPath: /actuator/health
    port: 8080