create sequence hibernate_sequence start with 1 increment by 1;
create table addresses (id varchar(255) not null, pin varchar(255), street varchar(255), primary key (id));
create table author (id integer not null, bookid integer, firstname varchar(255), lastname varchar(255), star_rating integer, primary key (id));
create table book (id integer not null, name varchar(255), pagecount varchar(255), primary key (id));
create table breeders (id varchar(255) not null, code varchar(255), name varchar(255), rating integer, location_id varchar(255), primary key (id));
create table documents (id varchar(255) not null, document_number varchar(255), name varchar(255), valid_until varchar(255), pet_id varchar(255), primary key (id));
create table images (id varchar(255) not null, cdn varchar(255), file varchar(255), path varchar(255), pet_id varchar(255), review_id varchar(255), evidence_id varchar(255), primary key (id));
create table locations (id varchar(255) not null, latitude varchar(255), longitude varchar(255), name varchar(255), address_id varchar(255), primary key (id));
create table pets (id varchar(255) not null, breed varchar(255), description varchar(255), dob varchar(255), gender varchar(255), image varchar(255), rating integer not null, title varchar(255), type varchar(255), type_code varchar(255), breeder_id varchar(255), location_id varchar(255), price_id varchar(255), primary key (id));
create table prices (id varchar(255) not null, amount float not null, currency_code varchar(255), primary key (id));
create table reviews (id varchar(255) not null, comment varchar(255), dis_like_count integer, like_count integer, breeder_id varchar(255), pet_id varchar(255), primary key (id));
alter table breeders add constraint FKby3q8u1xnlmyvmqgx763tf30n foreign key (location_id) references locations;
alter table documents add constraint FKaofreiv47n3icqy8mlpfjv2m7 foreign key (pet_id) references pets;
alter table images add constraint FK98byvs8ghuojf31pv1ajiihmo foreign key (pet_id) references pets;
alter table images add constraint FKldf2s8wlcsqgmmrokc6syxw5q foreign key (review_id) references reviews;
alter table images add constraint FK1h1196k1c8820rj1r90yldvqv foreign key (evidence_id) references reviews;
alter table locations add constraint FKd0253cj4ou9w19m1vwbitcqme foreign key (address_id) references addresses;
alter table pets add constraint FK8k6mbxrub7pdh7850ejnnku76 foreign key (breeder_id) references breeders;
alter table pets add constraint FKdt2oerri32m1yhmbiqa66aiqc foreign key (location_id) references locations;
alter table pets add constraint FKnwqnvtbmvea1ffn5vbp3f81vd foreign key (price_id) references prices;
alter table reviews add constraint FKhg8lq56yyc8xdokp6afitfawb foreign key (breeder_id) references breeders;
alter table reviews add constraint FK4fr85vfa42957rsm2v0jjkx0g foreign key (pet_id) references pets